apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
  name: rhoda
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-dbaas-operator
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: dbaas-operator
      namespace: openshift-dbaas-operator
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: dbaas-operator
      namespace: openshift-dbaas-operator
    spec:
      source: dbaas-operator
      sourceNamespace: openshift-marketplace
      name: dbaas-operator
      installPlanApproval: Automatic
      channel: alpha
      startingCSV: dbaas-operator.v0.1.5

